api/urls.py
from django.urls import path, include

from rest_framework import routers
from api import views

app_name = "api"

router = routers.DefaultRouter()
router.register(r"reported_services", views.ReportedServiceViewSet, basename='reported_services')
router.register(r"reported_services_paid_cleaner", views.ReportedServicePaidCleanerViewSet, basename='reported_services_paid_cleaner')
router.register(r"availability", views.AvailabilityViewSet, basename='availability')
router.register(r"availability_updated", views.AvailabilityUpdatedViewSet, basename='availability_updated')
router.register(r"job", views.JobViewSet, basename='job')
router.register(r"client", views.ClientViewSet, basename='client')
router.register(r"job_cleaner", views.JobCleanerViewSet, basename='job_cleaner')
router.register(r"cleaner", views.CustomUserViewSet, basename='cleaner')

urlpatterns = [
    path("", include(router.urls)),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    # Local
    path("", include("dashboard.urls")),
    path("users/", include("django.contrib.auth.urls")),
    path("accounts/", include("users.urls")),
    path("accounts/", include("allauth.urls")),
    path("api/", include("api.urls")),
    path("admins/", admin.site.urls),
    # Third party
    path("hijack/", include("hijack.urls", namespace="hijack")),
    # Utility
    path('favicon.ico', RedirectView.as_view(url='/static/images/favicon.ico')),
    # robots.txt
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
]




if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = "dashboard"

urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard_view"),
    path("availability/", views.AvailabilityListView.as_view(), name="availability_view"),
    path("availability/create/", views.AvailabilityCreateView.as_view(), name="availability_create_view",),
    path("availability/<int:pk>/update/", views.AvailabilityUpdateView.as_view(), name="availability_update_view",),
    path("availability/<int:pk>/delete/", views.AvailabilityDeleteView.as_view(), name="availability_delete_view",),
    path("jobs/", views.JobListView.as_view(), name="jobs_view"),
    path("jobs/<int:pk>/", views.JobDetailView.as_view(), name="job_view"),
    path("report/", views.ReportedServiceListView.as_view(), name="report_view"),
    path("report/history/", views.ReportHistoryView.as_view(), name="report_history_view"),
    path("report/submit/", views.SubmitReportFormView.as_view(), name="report_submit_view"),
    path("report/create/", views.ReportedServiceCreateView.as_view(), name="report_create_view",),
    path("report/mark-as-paid/", views.ReportedServiceFeesDue.as_view(), name="fees_due_view",),
    path("report/<int:pk>/update/", views.ReportedServiceUpdateView.as_view(), name="report_update_view",),
    path("report/<int:pk>/delete/", views.ReportedServiceDeleteView.as_view(), name="report_delete_view",),
    path("office_note/<int:pk>/read/", views.OfficeNoteReadReceiptUpdateView.as_view(), name="office_note_read_view",),

]

templates/403_csrf.html
{% extends 'base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/base.html
{% load static %}
{% load media %}
{% load hijack_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <title>{% block title %}Excel Cleaning{% endblock title %}</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="robots" content="noindex, nofollow">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

    {% block css %}
        <!-- Bootstrap CSS -->
        {% include_css "bootstrap.css" %}
        <!-- 3rd Party CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'hijack/hijack-styles.css' %}" />
        {% include_css "jquery-ui.css" %}
        <!-- Project CSS -->
        {% include_css "base.css" %}
    {% endblock %}
</head>

<body>
    {% hijack_notification %}
    <span class="d-none d-md-block">
        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <nav class="navbar navbar-light bg-light">
                <img src="{% static 'images/logo_blue.svg' %}" width="92" height="44" alt="Excel Cleaning">
            </nav>
            <div class="collapse navbar-collapse">
                {% if user.is_authenticated and not hide_nav %}
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item {% if page == 'dashboard' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'dashboard:dashboard_view' %}">Dashboard</a>
                        </li>
                        <li class="nav-item {% if page == 'availability' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'dashboard:availability_view' %}">Availability</a>
                        </li>
                        <li class="nav-item {% if page == 'jobs' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'dashboard:jobs_view' %}">Jobs</a>
                        </li>
                        <li class="nav-item {% if page == 'report' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'dashboard:report_view' %}">Report</a>
                        </li>
                    </ul>
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.first_name }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                        <a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a>
                    </div>
                {% endif %}
            </div>
        </nav>
    </span>

    {% if user.is_authenticated and not hide_nav %}
        <nav class="navbar navbar-expand fixed-bottom navbar-dark bg-dark d-block d-md-none">
            <div class="mobile_menu">
                <a class="item blue no_link {% if page == 'dashboard' %}active{% endif %}" href="{% url 'dashboard:dashboard_view' %}">
                    <div>
                        <img src="{% static 'images/icons/info-circle.svg' %}" alt="" width="20" height="20">
                    </div>
                    <div class="pt-1">Dashboard</div>
                </a>
                <a class="item blue no_link {% if page == 'availability' %}active{% endif %}" href="{% url 'dashboard:availability_view' %}">
                    <div>
                        <img src="{% static 'images/icons/calendar.svg' %}" alt="" width="20" height="20">
                    </div>
                    <div class="pt-1">Availability</div>

                </a>
                <a class="item blue no_link {% if page == 'jobs' %}active{% endif %}" href="{% url 'dashboard:jobs_view' %}">
                    <div>
                        <img src="{% static 'images/icons/house.svg' %}" alt="" width="20" height="20">
                    </div>
                    <div class="pt-1">Jobs</div>
                </a>
                <a class="item blue no_link {% if page == 'report' %}active{% endif %}" href="{% url 'dashboard:report_view' %}">
                    <div>
                        <img src="{% static 'images/icons/pencil-square.svg' %}" alt="" width="20" height="20">
                    </div>
                    <div class="pt-1">Report</div>
                </a>
            </div>
        </nav>
    {% endif %}

    {% block content %}
        <p>Default content...</p>
    {% endblock content %}

    <footer class="footer d-none d-md-block">
        <div class="container text-center ">
            <span class="text-muted small">Made with ❤️ by Excel Cleaning</span>
        </div>
    </footer>

    {% block javascript %}
        <!-- Bootstrap JavaScript -->
        {% include_js "jquery.js" %}
        {% include_js "jsdelivr.js" %}
        {% include_js "bootstrap.js" %}
        <!-- 3rd party JavaScript -->
        {% include_js "jquery-ui.js" %}
        <!-- Project JS -->
        {% include_js "base.js" %}
    {% endblock javascript %}

</body>

</html>

templates/lockout.html
<h1>Too many incorrect log in attempts</h1>
<p>Please try again in one hour.</p>