api/urls.py
from django.urls import path, include

from rest_framework import routers
from api import views

app_name = "api"

router = routers.DefaultRouter()
router.register(r"reported_services", views.ReportedServiceViewSet, basename='reported_services')
router.register(r"reported_services_paid_cleaner", views.ReportedServicePaidCleanerViewSet, basename='reported_services_paid_cleaner')
router.register(r"availability", views.AvailabilityViewSet, basename='availability')
router.register(r"availability_updated", views.AvailabilityUpdatedViewSet, basename='availability_updated')
router.register(r"job", views.JobViewSet, basename='job')
router.register(r"client", views.ClientViewSet, basename='client')
router.register(r"job_cleaner", views.JobCleanerViewSet, basename='job_cleaner')
router.register(r"cleaner", views.CustomUserViewSet, basename='cleaner')

urlpatterns = [
    path("", include(router.urls)),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    # Local
    path("", include("dashboard.urls")),
    path("users/", include("django.contrib.auth.urls")),
    path("accounts/", include("users.urls")),
    path("accounts/", include("allauth.urls")),
    path("api/", include("api.urls")),
    path("admins/", admin.site.urls),
    # Third party
    path("hijack/", include("hijack.urls", namespace="hijack")),
    # Utility
    path('favicon.ico', RedirectView.as_view(url='/static/images/favicon.ico')),
    # robots.txt
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
]




if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = "dashboard"

urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard_view"),
    path("availability/", views.AvailabilityListView.as_view(), name="availability_view"),
    path("availability/create/", views.AvailabilityCreateView.as_view(), name="availability_create_view",),
    path("availability/<int:pk>/update/", views.AvailabilityUpdateView.as_view(), name="availability_update_view",),
    path("availability/<int:pk>/delete/", views.AvailabilityDeleteView.as_view(), name="availability_delete_view",),
    path("jobs/", views.JobListView.as_view(), name="jobs_view"),
    path("jobs/<int:pk>/", views.JobDetailView.as_view(), name="job_view"),
    path("report/", views.ReportedServiceListView.as_view(), name="report_view"),
    path("report/history/", views.ReportHistoryView.as_view(), name="report_history_view"),
    path("report/submit/", views.SubmitReportFormView.as_view(), name="report_submit_view"),
    path("report/create/", views.ReportedServiceCreateView.as_view(), name="report_create_view",),
    path("report/mark-as-paid/", views.ReportedServiceFeesDue.as_view(), name="fees_due_view",),
    path("report/<int:pk>/update/", views.ReportedServiceUpdateView.as_view(), name="report_update_view",),
    path("report/<int:pk>/delete/", views.ReportedServiceDeleteView.as_view(), name="report_delete_view",),
    path("office_note/<int:pk>/read/", views.OfficeNoteReadReceiptUpdateView.as_view(), name="office_note_read_view",),

]

dashboard/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import (CreateView, DeleteView, FormView,
                                       UpdateView)
from sentry_sdk import capture_exception

from dashboard.forms import (CreateAvailabilityForm,
                             CreateUpdateReportedServiceForm,
                             OfficeNoteReadReceiptForm,
                             ReportedServiceMarkAsPaidForm, SubmitReportForm)
from dashboard.models import (Availability, Job, JobCleaner,
                              OfficeNoteReadReceipt, ReportedService)
from dashboard.utilities import time_to_float, timedelta_to_float


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/dashboard.html"

    def render_to_response(self, context, **response_kwargs):
        # check if the user needs to change their password
        if self.request.user and self.request.user.password_expired:
            messages.error(self.request, "Your password has expired. You need to create a new password.")
            return redirect(reverse('users:account_change_password'))
        else:
            # use normal method
            response_kwargs.setdefault('content_type', self.content_type)
            return self.response_class(
                request=self.request,
                template=self.get_template_names(),
                context=context,
                using=self.template_engine,
                **response_kwargs
            )

    def get_context_data(self, **kwargs):
        # mark messages as read (this is from sign in / sign out)
        storage = messages.get_messages(self.request)
        for msg in storage:
            msg.used = True

        context = super().get_context_data(**kwargs)
        context["page"] = "dashboard"
        context["office_notes"] = self.request.user.get_unread_office_notes()
        context["cleaner_payment_amount"] = self.request.user.get_cleaner_payment_amount()
        context["reported_services_owed"] = self.request.user.get_reported_services_owed()
        context["fees_owing"] = self.request.user.get_fees_owing()
        context["unsubmitted_services_count"] = self.request.user.unsubmitted_services_count()
        return context


class AvailabilityListView(LoginRequiredMixin, ListView):
    model = Availability
    context_object_name = "availability_list_this_week"

    def get_queryset(self):
        return Availability.objects.filter(user=self.request.user, week=0)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["availability_list_next_week"] = Availability.objects.filter(
            user=self.request.user, week=1
        )
        context["page"] = "availability"
        today = timezone.localdate()
        context["this_week_mon"] = today - datetime.timedelta(days=today.weekday())
        context["this_week_sun"] = context["this_week_mon"] + datetime.timedelta(days=6)
        context["next_week_mon"] = context["this_week_sun"] + datetime.timedelta(days=1)
        context["next_week_sun"] = context["next_week_mon"] + datetime.timedelta(days=6)
        return context


class AvailabilityCreateView(LoginRequiredMixin, CreateView):
    model = Availability
    form_class = CreateAvailabilityForm
    template_name_suffix = "_create_update_form"
    success_url = reverse_lazy("dashboard:availability_view")

    def form_valid(self, form):
        try:
            form.process(self)
            return super().form_valid(form)
        except ValueError as e:
            capture_exception(e)
            return self.render_to_response(self.get_context_data(form=form, error=e))

    def get_initial(self, *args, **kwargs):
        initial = super(AvailabilityCreateView, self).get_initial(**kwargs)
        initial["user"] = self.request.user
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page"] = "availability"
        context["page_type"] = "create"
        context["error"] = kwargs.get("error")
        today = timezone.localdate()
        monday_this_week = today - datetime.timedelta(days=today.weekday())
        context["week_dates"] = []
        for x in range(14):
            to_add = monday_this_week + datetime.timedelta(days=x)
            context["week_dates"].append(to_add)

        return context


class AvailabilityUpdateView(LoginRequiredMixin, UpdateView):
    model = Availability
    form_class = CreateAvailabilityForm
    template_name_suffix = "_create_update_form"
    success_url = reverse_lazy("dashboard:availability_view")

    def form_valid(self, form):
        try:
            form.process(self)
            return super().form_valid(form)
        except ValueError as e:
            capture_exception(e)
            return self.render_to_response(self.get_context_data(form=form, error=e))

    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(**kwargs)
        start_minute = 0.5 if self.object.start_time.minute else 0
        initial["start_time_"] = self.object.start_time.hour + start_minute
        end_minute = 0.5 if self.object.end_time.minute else 0
        initial["end_time_"] = self.object.end_time.hour + end_minute
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page"] = "availability"
        context["page_type"] = "update"
        today = timezone.localdate()
        monday_this_week = today - datetime.timedelta(days=today.weekday())
        context["week_dates"] = []
        for x in range(14):
            to_add = monday_this_week + datetime.timedelta(days=x)
            context["week_dates"].append(to_add)

        return context


class AvailabilityDeleteView(LoginRequiredMixin, DeleteView):
    model = Availability
    template_name_suffix = "_confirm_delete"
    success_url = reverse_lazy("dashboard:availability_view")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page"] = "availability"
        return context

    def post(self, request, *args, **kwargs):
        """Overwrite post to fail gracefully on Availability.DoesNotExist."""
        try:
            return self.delete(request, *args, **kwargs)
        except Http404:
            return HttpResponseRedirect(self.success_url)


class JobListView(LoginRequiredMixin, ListView):
    model = Job
    context_object_name = "jobs"

    def get_queryset(self):
        job_ids = JobCleaner.objects.filter(user=self.request.user).values_list(
            "job__id", flat=True
        )
        return Job.objects.filter(id__in=job_ids)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page"] = "jobs"
        return context


class JobDetailView(LoginRequiredMixin, DetailView):
    model = Job

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page"] = "jobs"
        return context


class ReportedServiceListView(LoginRequiredMixin, ListView):
    model = ReportedService
    context_object_name = "completed_services"

    def get_queryset(self):
        return ReportedService.objects.filter(
            user=self.request.user, status=3, submitted=None
        ).order_by("date_time")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page"] = "report"
        context["cancelled_services"] = ReportedService.objects.filter(
            user=self.request.user, status=2, submitted=None
        )
        context["submit_report_form"] = SubmitReportForm
        context["jobs"] = JobCleaner.objects.filter(user=self.request.user).exists()
        context["fees_owing"] = self.request.user.get_fees_owing()
        return context

    def post(self, request, *args, **kwargs):
        return SubmitReportFormView.as_view()(request)


class SubmitReportFormView(LoginRequiredMixin, SuccessMessageMixin, FormView):
    form_class = SubmitReportForm
    template_name = "dashboard/reportedservice_confirm_submit.html"
    success_url = reverse_lazy("dashboard:fees_due_view")
    success_message = "Services successfully submitted."

    def form_valid(self, form):
        reported_services = ReportedService.objects.filter(
            user=self.request.user, submitted=None
        )
        reported_services.update(submitted=timezone.localtime())
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page"] = "report"
        return context


class ReportedServiceCreateView(LoginRequiredMixin, CreateView):
    model = ReportedService
    form_class = CreateUpdateReportedServiceForm
    template_name_suffix = "_create_update_form"
    success_url = reverse_lazy("dashboard:report_view")

    def form_valid(self, form):
        try:
            form.process(self)
            return super().form_valid(form)
        except ValueError as e:
            capture_exception(e)
            return self.render_to_response(self.get_context_data(form=form, error=e))

    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(**kwargs)
        initial["user"] = self.request.user
        jobs = self.request.user.get_jobs()
        initial["jobs"] =jobs
        initial["invoice_jobs"] = ",".join(
            map(str, jobs.filter(invoice_job=True).values_list("id", flat=True))
        )

templates/dashboard/availability_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page_title_container">
    <div class="left">
        <a href="{% url 'dashboard:availability_view' %}">
            <img class="item white d-inline-block d-md-none" src="{% static 'images/icons/chevron-left.svg' %}" alt="" width="20" height="20">
            <span class="d-none d-md-inline-block btn btn-outline-secondary btn-sm">
                <img class="item no_margin grey" src="{% static 'images/icons/chevron-left.svg' %}" alt="" width="20" height="20">
                Availability
            </span>
        </a>
    </div>
    <div class="page_title">Delete Availability</div>
    <div class="right"></div>
</div>



<div class="body_container">
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <button type="submit" class="btn btn-danger btn_block">Delete</button>
    </form>
</div>

{% endblock content %}

templates/dashboard/availability_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Clients{% endblock title %}

{% block content %}

<div class="page_title_container">
    <div class="left"></div>
    <div class="page_title">Availability</div>
    <div class="right">
        <a href="{% url 'dashboard:availability_create_view' %}">
            <span class="add_icon d-inline-block d-md-none">+</span>
            <span class="d-none d-md-inline-block btn btn-primary btn-sm">+ Availability</span>
        </a>

    </div>
</div>

{% if availability_list_this_week or availability_list_next_week %}
    <div class="body_container no_gutter no_top">
        {% if availability_list_this_week %}
            <div class="list_title">
                This Week
                <span class="datetime_grey">
                    ({{ this_week_mon|date:'M j' }} - {{ this_week_sun|date:'M j' }})
                </span>
            </div>
            <ul class="list_view">
                {% for availability in availability_list_this_week %}
                    <li>
                        <div>
                            <span class="hide_on_smallest">{{ availability.get_day|date:'l' }}</span>
                            <span class="show_on_smallest">{{ availability.get_day|date:'D' }}</span>
                            {{ availability.start_time|date:'g:i A'|lower}} -
                            {{ availability.end_time|date:'g:i A'|lower }}
                        </div>
                        <div class="update_delete_container">
                            <a href="{% url 'dashboard:availability_update_view' pk=availability.id %}"><img class="item active blue" src="{% static 'images/icons/pencil.svg' %}" alt="" width="18" height="18"></a>
                            <a href="{% url 'dashboard:availability_delete_view' pk=availability.id %}"><img class="item red" src="{% static 'images/icons/trash.svg' %}" alt="" width="18" height="18"></a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if availability_list_next_week %}
            <div class="list_title">
                Next Week
                <span class="datetime_grey">
                    ({{ next_week_mon|date:'M j' }} - {{ next_week_sun|date:'M j' }})
                </span>
            </div>
            <ul class="list_view">
                {% for availability in availability_list_next_week %}
                    <li>
                        <div>
                            <span class="hide_on_smallest">{{ availability.get_day|date:'l' }}</span>
                            <span class="show_on_smallest">{{ availability.get_day|date:'D' }}</span>
                            {{ availability.start_time|date:'g:i a' }} -
                            {{ availability.end_time|date:'g:i a' }}
                        </div>
                        <div class="update_delete_container">
                            <a href="{% url 'dashboard:availability_update_view' pk=availability.id %}"><img class="item active blue" src="{% static 'images/icons/pencil.svg' %}" alt="" width="18" height="18"></a>
                            <a href="{% url 'dashboard:availability_delete_view' pk=availability.id %}"><img class="item red" src="{% static 'images/icons/trash.svg' %}" alt="" width="18" height="18"></a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% else %}
    <div class="body_container text-center">
        <img class="mt-3 mb-4" src="{% static 'images/icons/exclamation-triangle.svg' %}" alt="" width="30" height="30">
        <p>You haven't recorded any availability.</p>
        <p>If you would like more work, please add your availability here.</p>
    </div>
{% endif %}



{% endblock content %}

templates/dashboard/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}Dashboard{% endblock title %}

{% block content %}
    <div class="page_title_container">
        <div class="left"></div>
        <div class="page_title">Dashboard</div>
        <div class="right">
            <a class="nav-link" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img class="white_icon" src="{% static 'images/icons/people-circle.svg' %}" alt="" width="20" height="20">
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                <a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a>
            </div>
        </div>
    </div>

    <div class="body_container">
        {% include 'dashboard/message.html' %}

        {% if fees_owing or cleaner_payment_amount %}
            <div class="page_section">
                <div class="page_body_heading">Fees</div>
                {% if fees_owing %}
                    <div>I owe Excel: <strong>${{ fees_owing|floatformat:"-2"|intcomma }}</strong></div>
                    <a class="btn btn-primary btn-sm btn_block mb-3 mt-2" href="{% url 'dashboard:fees_due_view' %}">View Fees Due</a>
                {% endif %}
                {% if cleaner_payment_amount %}
                    <div class="pb-2">
                        <div class="pb-2">Excel owes me: <strong>${{ cleaner_payment_amount|floatformat:"-2"|intcomma }}</strong></div>
                        <ul>
                            {% for service in reported_services_owed %}
                                <li>
                                    {{ service }}:
                                    ${{ service.get_payment_owed|floatformat:"-2"|intcomma }}
                                    ({{ service.date_time|date:"j/n/y" }})
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        {% endif %}

        {% if unsubmitted_services_count %}
            <div class="page_section">
                <div class="page_body_heading">Submit Reported Services to Excel</div>
                <p>You have {{ unsubmitted_services_count|apnumber }} reported service{{ unsubmitted_services_count|pluralize:",s" }} saved which {{ unsubmitted_services_count|pluralize:"has,have" }} not been submitted to Excel.</p>
                <a class="btn btn-primary btn-sm btn_block mb-3 mt-2" href="{% url 'dashboard:report_view' %}">View Service{{ unsubmitted_services_count|pluralize:",s" }} To Submit</a>
            </div>
        {% endif %}

        <div class="page_section">
            <div class="page_body_heading">Note from the Office</div>
            {% if office_notes %}
                {% for receipt in office_notes %}
                    {% if not forloop.first %}
                        <div class="note_break"></div>
                    {% endif %}
                    {% if receipt.office_note.title %}
                        <h5>{{ receipt.office_note.title }}</h5>
                    {% endif %}
                    {% if not receipt.office_note.hide_live_at %}
                        <span class="text-muted small">{{ receipt.office_note.live_at|naturaltime }}</span>
                    {% endif %}
                    <div class="mt-2 mb-4">{{ receipt.office_note.note|safe|linebreaks }}</div>
                    <a class="btn btn-primary btn-sm btn_block" href="{% url 'dashboard:office_note_read_view' receipt.id %}">Mark as Read</a>

                {% endfor %}

            {% else %}
                <div class="text-center">
                    No news! <br><br>¯\_(ツ)_/¯
                </div>
            {% endif %}
        </div>



        {% if scheduled_services %}
            <div class="page_section">
                <div class="page_body_heading">Upcoming services</div>
                {% for service in scheduled_service %}
                    <p>{{ service }}</p>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock content %}

templates/dashboard/job_detail.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% load humanize %}

{% block title %}Jobs{% endblock title %}

{% block content %}

<div class="page_title_container">
    <div class="left">
        <a href="{% url 'dashboard:jobs_view' %}">
            <img class="item white d-inline-block d-md-none" src="{% static 'images/icons/chevron-left.svg' %}" alt="" width="20" height="20">
            <span class="d-none d-md-inline-block btn btn-outline-secondary btn-sm">
                <img class="item no_margin grey" src="{% static 'images/icons/chevron-left.svg' %}" alt="" width="20" height="20">
                Jobs
            </span>
        </a>
    </div>
    <div class="page_title">{{ job }}</div>
    <div class="right"></div>
</div>

<div class="body_container">
    <div class="page_section">
        <div class="page_body_heading">Address</div>
        <div>{{ job.get_address }}</div>
    </div>
    <div class="page_section">
        <div class="page_body_heading">Fee Details</div>
        <div>
        {% if job.invoice_job %}
            <p>This is an invoice job, where the client pays Excel and Excel pays you{% if job.cleaner_hourly_rate %} ${{ job.cleaner_hourly_rate|floatformat:"-2"|intcomma }} per hour{% endif %}.</p>
        {% elif job.excel_fee %}
            <p>The agency fee for this job is ${{ job.excel_fee|floatformat:"-2"|intcomma }} per service.</p>
        {% endif %}
        {% if job.byo_cleaner_fee %}
            <p>This service includes a BYO fee (products and equipment) of ${{ job.byo_cleaner_fee|floatformat:"-2"|intcomma }} per service.
        {% endif %}
        </div>
    </div>
    <div class="page_section">
        <div class="page_body_heading">Contact Details</div>
        {% for client in job.clients.all %}
            <div>
                {{ client }}: {% for phone in client.get_phones %}{% if forloop.counter > 1 %},{% endif %} <a href="tel:{{ phone|format_international }}">{{ phone|format_phone }}</a>{% endfor %}
            </div>
        {% endfor %}
    </div>
    {% if job.last_service %}
        <div class="page_section">
            <div class="page_body_heading">Job Details</div>
            <div>Last service: {{ job.last_service }}</div>
        </div>
    {% endif %}

</div>
{% endblock content %}

templates/dashboard/job_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Jobs{% endblock title %}

{% block content %}

<div class="page_title_container">
    <div class="left"></div>
    <div class="page_title">Jobs</div>
    <div class="right"></div>
</div>

<div class="body_container no_gutter">
    {% if jobs %}
        <ul class="list_view">
            {% for job in jobs %}
            <a class="no_link" href="{% url 'dashboard:job_view' pk=job.id %}">
                <img class="item grey" src="{% static 'images/icons/person-fill.svg' %}" alt="" width="30" height="30">
                <li>
                    {{ job }}
                </li>
            </a>
            {% endfor %}
        </ul>
    {% else %}
        <div class="text-center">
            <img class="mt-3 mb-4" src="{% static 'images/icons/exclamation-triangle.svg' %}" alt="" width="30" height="30">
            <p>You don't have any jobs yet.</p>
            <p>If you're wanting work, please make sure your availability is up to date <a href="{% url 'dashboard:availability_view' %}">here</a>.</p>
        </div>
    {% endif %}
</div>

{% endblock content %}

templates/dashboard/message.html
{% if messages %}
        {% for message in messages %}
        <div class="messages alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}">
            {{ message|safe }}
        </div>
        {% endfor %}
{% endif %}

templates/dashboard/office_note_confirm_read.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}


<div class="page_title_container">
    <div class="left">
        <a href="{% url 'dashboard:dashboard_view' %}">
            <img class="item white d-inline-block d-md-none" src="{% static 'images/icons/chevron-left.svg' %}" alt="" width="20" height="20">
            <span class="d-none d-md-inline-block btn btn-outline-secondary btn-sm">
                <img class="item no_margin grey" src="{% static 'images/icons/chevron-left.svg' %}" alt="" width="20" height="20">
                Dashboard
            </span>
        </a>
    </div>
    <div class="page_title">Mark As Read</div>
    <div class="right"></div>
</div>

<div class="body_container">
    <p class="py-4">Are you sure you want to mark this message as read?</p>
    {% crispy form %}
</div>


{% endblock content %}

templates/dashboard/reportedservice_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}Clients{% endblock title %}

{% block content %}

    <div class="page_title_container">
        <div class="left"></div>
        <div class="page_title">Report</div>
        <div class="right">
            {% if jobs %}
                <a href="{% url 'dashboard:report_create_view' %}" class="">
                    <span class="add_icon d-inline-block d-md-none">+</span>
                    <span class="d-none d-md-inline-block btn btn-primary btn-sm">+ Service</span>
                </a>
            {% endif %}
        </div>
    </div>


    {% if completed_services or cancelled_services %}
        <div class="body_container no_gutter no_top">
            {% if completed_services %}
                <div class="list_title">Completed services</div>
                <ul class="list_view">
                    {% for service in completed_services %}
                        <li>
                            <div>
                                <div>{{ service }}</div>
                                <div class="datetime_grey">
                                    {{ service.date_time|date:"D" }},
                                    <span class="hide_on_smallest">{{ service.date_time|date:"F j, Y" }}</span>
                                    <span class="show_on_smallest">{{ service.date_time|date:"M j, Y" }} </span>
                                    ({{ service.date_time|date:'g:i A'|lower }})
                                </div>
                            </div>
                            <div class="update_delete_container">
                                <a href="{% url 'dashboard:report_update_view' pk=service.id %}"><img class="item active blue" src="{% static 'images/icons/pencil.svg' %}" alt="" width="18" height="18"></a>
                                <a href="{% url 'dashboard:report_delete_view' pk=service.id %}"><img class="item red" src="{% static 'images/icons/trash.svg' %}" alt="" width="18" height="18"></a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
            {% if cancelled_services %}
                <div class="list_title">Cancelled services</div>
                <ul class="list_view">
                    {% for service in cancelled_services %}
                        <li>
                            <div>
                                <div>{{ service }}</div>
                                <div class="datetime_grey">{{ service.date_time|date:"D, F j, Y" }}</div>
                            </div>
                            <div class="update_delete_container">
                                <a href="{% url 'dashboard:report_update_view' pk=service.id %}"><img class="item active blue" src="{% static 'images/icons/pencil.svg' %}" alt="" width="18" height="18"></a>
                                <a href="{% url 'dashboard:report_delete_view' pk=service.id %}"><img class="item red" src="{% static 'images/icons/trash.svg' %}" alt="" width="18" height="18"></a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
            <div class="container pt-4">
                <a class="btn btn-success btn_block" href="{% url 'dashboard:report_submit_view' %}">Submit To Excel</a>
            </div>
            <div class="text-center pt-5">See <a href="{% url 'dashboard:report_history_view' %}">previously reported services</a>.</div>
        </div>
    {% elif not jobs %}
        <div class="body_container text-center">
            {% include 'dashboard/message.html' %}
            <img class="mt-3 mb-4" src="{% static 'images/icons/exclamation-triangle.svg' %}" alt="" width="30" height="30">
            <p>You don't have any jobs yet.</p>
            <p>If you're wanting work, please make sure your availability is up to date <a href="{% url 'dashboard:availability_view' %}">here</a>.</p>
        </div>
    {% else %}
        <div class="body_container text-center">
            <p>No services to submit.</p>
            <div class="pt-5">See <a href="{% url 'dashboard:report_history_view' %}">previously reported services</a>.</div>
        </div>
    {% endif %}

{% endblock content %}